# Generated by Django 3.1.4 on 2020-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_full',
            field=models.TextField(default='texttexttext', verbose_name='Полный текст'),
            preserve_default=False,
        ),
    ]
