# Generated by Django 3.1.4 on 2020-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_content_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_full',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
    ]
